[package]
edition = "2021"
name = "anewer"
version = "0.2.1"
authors = ["ysf <ich@youssef.de>"]
description = "anewer appends only new lines from stdin to a file."
homepage = "https://github.com/ysf/anewer"
repository = "https://github.com/ysf/anewer"
categories = ["command-line-utilities"]
keywords = ["cli", "io", "uniq"]
readme = "README.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
    ".gitignore",
    "RECIPES.md",
    "docs/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
ahash = "0.8"
memchr = "2.8"

[[bin]]
name = "anewer"
test = false
bench = false
