name: Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose --release

    - name: Strip binary
      run: strip target/release/anewer

    - name: Archive executable
      uses: actions/upload-artifact@v4
      with:
        name: anewer
        path: target/release/anewer
